-- SCE Programs from CSV
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SCE_WILLDAN_CEEP_2025', 'Commercial Energy Efficiency Program (CEEP)', 'Southern California Edison', 'https://willdanefficiency.com/rebates', 'Prescriptive Rebates + Custom program for Commercial (all sizes). Active SCE non‑res account; equipment must meet CA eTRM; used/rebuilt not eligible', 'HPWH 45–99 gal: $6k–$8k; HPWH 120 gal: $14k–$25k by building type (CZ15 lower); DCKV: $1,900/HP; ASH Controls: $65/LF; Medium Temp Case Doors: $230/LF; SRM motors: $425/HP', '["Commercial"]', '["Refrigeration", "Motors", "Water Heating"]', 'Prescriptive', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SCE_AESC_MSP_2025', 'Measured Savings Program (MSP)', 'Southern California Edison', 'https://aesc-inc.com/measured-savings-program/', 'Pay‑for‑Performance (NMEC) program for Commercial & Public. Active SCE account; NAICS in Appendix A; 12 months AMI; baseline CV(RMSE)<0.50; <10% missing data/mo', 'Pop‑NMEC: $0.48 per TSB; Site‑NMEC: $0.46 per TSB; pre‑payment + interim/final true‑ups after 12‑mo M&V', '["Commercial", "Commercial"]', '["Energy Efficiency"]', 'Performance-Based', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SCE_GRID_MAP_2025', 'Grid‑Responsive Incentive Design – Market Access Program (GRID‑MAP)', 'Southern California Edison', 'https://mendotagroup.com/GRID-MAP-for-SCE/', 'Market Access (NMEC) program for Commercial & Residential (incl. C&I). Active SCE account; PPP surcharge; 12 months AMI; no Rule 24 DR; no onsite gen changes ±12 months; no double‑dipping', 'Avoided‑cost‑weighted metered savings; rates vary annually with avoided costs', '["Commercial", "Residential"]', '["Energy Efficiency"]', 'Performance-Based', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SCE_CERI_2025', 'Commercial Energy Reduction Initiative (CERI)', 'Southern California Edison', 'https://socalceri.com/', 'Custom Projects (audit + reservation + M&V) program for Healthcare, High‑Tech, Biotech, Higher Ed; Unserved <200 kW. Active meter in listed SoCal counties; subsectors listed; case‑by‑case approval', 'Customized incentives reserved with utility; payout after verified savings', '["Commercial"]', '["Energy Efficiency"]', 'Custom', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SCE_PEP_COMM_SEM_2025', 'Local Commercial Strategic Energy Management (SEM)', 'Southern California Edison', 'https://pep.clearesult.com/pep/commercial', 'SEM (whole‑facility NMEC) program for Commercial. SCE commercial customers; program enrollment via PEP', 'Rebates/incentives tied to SEM actions and metered savings; long‑term coaching (up to 6 years)', '["Commercial"]', '["Strategic Energy Management"]', 'Performance-Based', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SCE_PEP_IND_AG_SEM_2025', 'Local Industrial & Agricultural SEM', 'Southern California Edison', 'https://pep.clearesult.com/pep/industrial-agriculture/', 'SEM (NMEC) program for Industrial & Agriculture. SCE industrial/ag sites; cohort participation', 'Incentives for capital + O&M savings under SEM with NMEC baselines', '["Industrial", "Agricultural"]', '["Strategic Energy Management"]', 'Performance-Based', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SCE_ELRP_2025', 'Emergency Load Reduction Program (ELRP)', 'Southern California Edison', 'https://elrp.sce.com/', 'Demand Response (emergency) program for Commercial & Industrial. Ability to curtail during emergencies; baseline/M&V rules apply', '$2.00/kWh reduced during events; no penalties for non‑performance', '["Commercial", "Industrial"]', '["Demand Response"]', 'Performance-Based', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SCE_AUTODR_EXPRESS_2025', 'Auto‑DR – Express Control Incentives', 'Southern California Edison', 'https://www.sce.com/business/save-costs-energy/savings-strategies-for-businesses/what-is-demand-response/automated-demand-response/auto-dr-express-control-incentives', 'Technology Incentives (enables DR) program for Commercial & Industrial. SCE non‑res account; device on qualified list; DR enrollment required', 'Menu‑based incentives for qualified controls/devices to automate DR reductions', '["Commercial", "Industrial"]', '["Demand Response"]', 'Performance-Based', 'open');

-- PG&E Programs (grouped by category)
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'PGE_AG_FOOD_VSD_2025', 'PG&E Agriculture & Food Processing VSD Rebates', 'Pacific Gas & Electric', 'https://www.pge.com/en/save-energy-and-money/energy-saving-programs/business-programs.html', 'Variable Speed Drive (VSD) rebates for dust collection fans in agriculture and food processing facilities. Covers motors from 10 HP to 150 HP with tiered rebates.', 'Rebates range from $250 (10 HP) to $15,000 (150 HP) per motor for dust collection fan VSDs. Requirements: NAICS ranges 111000-112990, 211120-213115, 311000-339999; feedback control on static pressure/CFM/velocity; no prior/failed VSD; submit ≤60 days.', '["Agricultural", "Industrial"]', '["Motors", "Agriculture"]', 'Prescriptive', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'PGE_HVAC_COMM_2025', 'PG&E Commercial HVAC Rebates', 'Pacific Gas & Electric', 'https://www.pge.com/en/save-energy-and-money/energy-saving-programs/business-programs.html', 'HVAC rebates for commercial buildings including VFDs for ventilation fans and advanced rooftop controls. Supports energy-efficient climate control systems.', 'VFD for HVAC Fan: $80/HP for existing fans. Advanced Rooftop HVAC Controls: $120-$194 per ton depending on package type and climate zone. Requirements: existing HVAC supply/return/exhaust fan; single-speed motor; remove throttling devices; submit ≤60 days.', '["Commercial"]', '["HVAC"]', 'Prescriptive', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'PGE_REFRIGERATION_2025', 'PG&E Commercial Refrigeration Rebates', 'Pacific Gas & Electric', 'https://www.pge.com/en/save-energy-and-money/energy-saving-programs/business-programs.html', 'Comprehensive refrigeration rebates for commercial applications including ultra-low temperature freezers, ASH controls, display case doors, and case replacements.', 'Ultra-Low Temp Freezers: $300-$600/unit (ENERGY STAR, -80°C capable). ASH Controls: $25/linear ft for medium & low temp. High-Efficiency Display Case Doors: $75/LF (low temp). Open Multi-Deck Case Replacements: $75-$175/LF. Requirements vary by measure; submit ≤60 days.', '["Commercial"]', '["Refrigeration"]', 'Prescriptive', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'PGE_BUILDING_SYSTEMS_2025', 'PG&E Building Systems Rebates', 'Pacific Gas & Electric', 'https://www.pge.com/en/save-energy-and-money/energy-saving-programs/business-programs.html', 'Rebates for various building systems including pipe/fitting insulation, ozone laundry systems, commercial pool heaters, and backup generators.', 'Pipe Insulation: $3/linear ft for various pipe sizes and applications. Ozone Laundry System: $39 per lb washer capacity. Commercial Pool & Spa Heater: $2 per MBtuh (≥84% TE). Generator Rebate: $300 per qualifying unit (HFRA Tier 2/3, ≥2 PSPS events). Submit ≤60 days.', '["Commercial", "Industrial"]', '["Insulation", "Water Heating", "Process Equipment"]', 'Prescriptive', 'open');

-- SDG&E Programs
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SDGE_PRESCRIPTIVE_2025', 'SDG&E Energy Efficiency Business Rebates - Prescriptive', 'San Diego Gas & Electric', 'https://www.sdge.com/businesses/savings-center/rebates-incentives', 'Fixed-amount equipment rebates for lighting improvements, refrigeration systems, natural gas technologies, food service equipment, and HVAC systems. Available to all business, industrial, and agricultural customers.', 'Pre-set rebate amounts for qualifying equipment including: Lighting improvements, Refrigeration systems, Natural gas technologies, Food service equipment, HVAC systems. Contact Energy Savings Center for specific rebate amounts.', '["Commercial", "Industrial", "Agricultural"]', '["Lighting", "Refrigeration", "HVAC", "Process Equipment"]', 'Prescriptive', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SDGE_CUSTOM_2025', 'SDG&E Energy Efficiency Business Rebates - Custom', 'San Diego Gas & Electric', 'https://www.sdge.com/businesses/savings-center/rebates-incentives', 'Performance-based incentives funding up to 50% of total project costs, calculated on direct energy (kWh or therms) saved. For projects that exceed government energy standards.', 'Up to 50% of total project costs based on direct energy savings (kWh or therms). Minimum requirement: Monthly electrical demand of at least 4,166 therms for certain programs. Projects must exceed government energy standards.', '["Commercial", "Industrial"]', '["Energy Efficiency"]', 'Custom', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SDGE_HVAC_COOLING_2025', 'SDG&E Premium Efficiency Cooling Program', 'San Diego Gas & Electric', 'https://www.sdge.com/businesses/savings-center/rebates-incentives', 'Low or no-cost HVAC tune-ups and incentives for new commercial HVAC equipment purchases to improve cooling efficiency.', 'Low or no-cost HVAC tune-ups plus incentives for purchasing new commercial HVAC equipment. Contact SDG&E Energy Savings Center for specific amounts.', '["Commercial"]', '["HVAC"]', 'Prescriptive', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SDGE_SMALL_BIZ_2025', 'SDG&E Energy Advantage Program for Small Business', 'San Diego Gas & Electric', 'https://www.sdge.com/businesses/savings-center/rebates-incentives', 'No-cost services for qualifying small businesses including energy assessments, audits, and referrals to contractors.', 'No-cost energy assessments, audits, and contractor referrals for qualifying small businesses. Free installation of eligible energy efficiency measures.', '["Commercial"]', '["Energy Efficiency"]', 'Direct Install', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SDGE_TECH_INCENTIVE_2025', 'SDG&E Technology Incentive Program', 'San Diego Gas & Electric', 'https://www.sdge.com/businesses/savings-center/rebates-incentives', 'Incentives for purchasing and installing automated equipment that syncs with SDG&E demand response measures to reduce usage during peak grid days.', 'Incentives for automated equipment installation that enables demand response participation. Equipment must be capable of syncing with SDG&E systems to reduce usage during peak grid events.', '["Commercial", "Industrial"]', '["Demand Response", "Energy Management"]', 'Technology', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SDGE_ENERGYLINK_2025', 'SD EnergyLink (Federal & Tribal)', 'San Diego Gas & Electric', 'https://www.sdge.com/businesses/savings-center/rebates-incentives', 'Cash incentives for customers on federal properties (military bases, post offices, federal agencies), Native American lands (18 recognized tribes), and local government facilities.', 'Cash incentives for energy efficiency improvements on federal and tribal lands. Apply online at sdenergylink.com. Available to federal properties, Native American tribal lands, and local government facilities.', '["Commercial", "Government"]', '["Energy Efficiency"]', 'Prescriptive', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SDGE_SGIP_2025', 'SGIP - Self-Generation Incentive Program (SDG&E)', 'San Diego Gas & Electric', 'https://www.sdge.com/businesses/savings-center/rebates-incentives', 'Battery energy storage incentives for businesses to reduce peak demand charges, provide backup during outages and PSPS events, and increase energy independence when paired with solar.', 'Incentives for battery energy storage systems. Reduces peak demand charges, provides backup power during outages and PSPS events. When paired with solar, increases energy independence. Visit sgipsd.org for current incentive rates.', '["Commercial", "Industrial"]', '["Energy Storage", "Solar"]', 'Technology', 'open');
INSERT INTO programs (source, source_program_id, name, owner, url, description, incentive_description, sector_tags, tech_tags, incentive_type, status)
VALUES ('utility', 'SDGE_DEMAND_RESPONSE_2025', 'SDG&E Demand Response Programs', 'San Diego Gas & Electric', 'https://www.sdge.com/businesses/savings-center/rebates-incentives', 'Get paid for reducing energy use during peak grid days. Multiple rates and incentive options available for commercial and industrial customers.', 'Payment for reducing energy consumption during peak grid events. Multiple program options with varying rates and requirements. Helps grid stability while reducing your energy costs.', '["Commercial", "Industrial"]', '["Demand Response"]', 'Performance-Based', 'open');

-- Geographic coverage (link all programs to their utilities)

-- SCE programs
INSERT INTO program_geos (program_id, state, utility_service_area) SELECT id, 'CA', 'Southern California Edison' FROM programs WHERE owner = 'Southern California Edison' AND source_program_id LIKE 'SCE_%';

-- PG&E programs
INSERT INTO program_geos (program_id, state, utility_service_area) SELECT id, 'CA', 'Pacific Gas & Electric' FROM programs WHERE owner = 'Pacific Gas & Electric' AND source_program_id LIKE 'PGE_%';

-- SDG&E programs
INSERT INTO program_geos (program_id, state, utility_service_area) SELECT id, 'CA', 'San Diego Gas & Electric' FROM programs WHERE owner = 'San Diego Gas & Electric' AND source_program_id LIKE 'SDGE_%';

-- Program summary
SELECT 'Total programs to be added:', COUNT(*) FROM (
  SELECT 1 FROM programs WHERE source_program_id LIKE 'SCE_%' UNION ALL
  SELECT 1 FROM programs WHERE source_program_id LIKE 'PGE_%' UNION ALL
  SELECT 1 FROM programs WHERE source_program_id LIKE 'SDGE_%'
) AS temp;
